// packages/react/src/components/react/src/Button/Button.jsx
"use client";
import * as React from "react";
import { useState } from "react";

function Button(props) {
  const [name, setName] = useState(() => "Foo");

  return (
    <div>
      {props.message || "Hello"}
      {name}! I can run in React, Vue, Solid or Svelte!
    </div>
  );
}

export default Button;

// packages/qwik/src/components/Button/Button.jsx
import { Fragment, component$, h, useStore } from "@builder.io/qwik";

export const Button = component$((props) => {
  const state = useStore({ name: "Foo" });

  return (
    <div>
      {props.message || "Hello"}
      {state.name}! I can run in React, Vue, Solid or Svelte!
    </div>
  );
});

export default Button;
